[package]
name = "smtp-xoauth2-test-tool"
version = "0.1.0"
edition = "2021"
author = "Lorenzo Leonardo <enzotechcomputersolutions@gmail.com>"

[dependencies]
async-curl = "0.1.7"
async-trait = "0.1.68"
chrono = "0.4.24"
curl-http-client = "0.1.1"
directories = "5.0.1"
env_logger = "0.10.0"
http = "0.2.9"
log = "0.4.17"
mail-send = "0.3.3"
oauth2 = { version = "4.3.0", default-features = false }
serde = "1.0.162"
serde_json = "1.0.96"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
