[package]
name = "smtp-xoauth2-test-tool"
version = "0.4.0"
edition = "2021"
author = "Lorenzo Leonardo <enzotechcomputersolutions@gmail.com>"

[dependencies]
async-curl = "0.3"
async-trait = "0.1"
chrono = "0.4"
curl-http-client = "1.0"
derive-deref-rs = "0.1"
directories = "5.0"
env_logger = "0.10"
http = "0.2"
log = "0.4"
mail-send = "0.3"
oauth2 = { version = "4.4", default-features = false }
serde = "1.0"
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.36", features = ["rt"] }
