[package]
name = "smtp-xoauth2-test-tool"
version = "0.1.0"
edition = "2021"
author = "Lorenzo Leonardo <enzotechcomputersolutions@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = { version = "4.3.0", default-features = false }
tokio = { version = "1.25.0", features = ["full"] }
thiserror = "1.0.37"
http = "0.2"
serde = "1.0.160"
serde_json = "1.0.96"
strum = "0.24"
strum_macros = "0.24"
curl = "0.4.44"
async-trait = "0.1.68"
mail-send = "0.3.3"
directories = "5.0.0"
env_logger = "0.10.0"
log = "0.4.17"
async-curl = "0.1.4"
